// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEeZvRSop6hMBFhd2g7g6CkNXUsSBTIvU',
    appId: '1:111103686317:web:b4fcd73e4dfb4d33f67824',
    messagingSenderId: '111103686317',
    projectId: 'daily-duties-33b73',
    authDomain: 'daily-duties-33b73.firebaseapp.com',
    storageBucket: 'daily-duties-33b73.appspot.com',
    measurementId: 'G-GD5VX80LFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABABfI2Gvs7xF4wIML6DWEb9DxtadPmLs',
    appId: '1:111103686317:android:3630695d0c08ac0cf67824',
    messagingSenderId: '111103686317',
    projectId: 'daily-duties-33b73',
    storageBucket: 'daily-duties-33b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_oPjNHHWy14FgLlTykXi8HCNK3Qt-TY',
    appId: '1:111103686317:ios:1d26be74c863470df67824',
    messagingSenderId: '111103686317',
    projectId: 'daily-duties-33b73',
    storageBucket: 'daily-duties-33b73.appspot.com',
    iosBundleId: 'com.tpnlabs.dailyduties',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_oPjNHHWy14FgLlTykXi8HCNK3Qt-TY',
    appId: '1:111103686317:ios:23b724a58160b389f67824',
    messagingSenderId: '111103686317',
    projectId: 'daily-duties-33b73',
    storageBucket: 'daily-duties-33b73.appspot.com',
    iosBundleId: 'com.tpnindustries.progressp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEeZvRSop6hMBFhd2g7g6CkNXUsSBTIvU',
    appId: '1:111103686317:web:e65b3c6ac0ae68c0f67824',
    messagingSenderId: '111103686317',
    projectId: 'daily-duties-33b73',
    authDomain: 'daily-duties-33b73.firebaseapp.com',
    storageBucket: 'daily-duties-33b73.appspot.com',
    measurementId: 'G-973WHDDK09',
  );
}
